# Generated by Django 4.2.6 on 2023-10-19 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userlibrary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlibrary",
            options={"verbose_name_plural": "UserLibraries"},
        ),
    ]
