# Generated by Django 4.2.6 on 2023-10-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_userlibrary_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
