# Generated by Django 4.2.6 on 2023-10-23 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlibrary",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
