# Generated by Django 4.2.6 on 2023-10-24 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_userlibrary_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userlibrary",
            old_name="product",
            new_name="products",
        ),
    ]
